### ISSUE TITLE
Exclude composer packages?

### ISSUE THREAD

**Issue by ginkgomzd** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#15]
Wouldn't it be better to not be checking in the vendor packages?
I saw John got tripped up over polyfill-php54 (PR#13). I wonder if there had been no dependencies present if it would have been more intuitive to have to run composer install to fetch all dependencies.

I note that I am not able to run composer update because of exceptions due to missing .git directories in vendor packages. Blowing them away and running update again resolves it just fine.

I haven't used composer enough to be real familiar with how it works. I'm wondering if the project is set up properly because it appears there are packages being tracked in the internal composer/installed.json that are not named in the top-project composer.json file. Maybe they are all sub-dependencies? I tried greping for polyfill-php54 and I could not see where it was declared as a dependency other than installed.json. I think this means that it was installed using composer install, checked in, but not added to the top-level composer.json. Maybe?

**Comment by eileenmcnaughton** [comment]
I think if I don't check in vendor I'm requiring installers to do that & mostly that is a bit too tricky for them. I agree it's not ideal but I feel like it probably needs to be resolved at the core level first.

**Comment by ginkgomzd** [comment]
FYI,
I blew away the vendor folder and after doing composer install, git reports:
	modified:   vendor/alfaproject/omnipay-skrill/tests/Omnipay/Skrill/GatewayTest.php
	modified:   vendor/autoload.php
	typechange: vendor/bin/phpcs
	deleted:    vendor/bin/phpcs.bat
	typechange: vendor/bin/phpunit
	deleted:    vendor/bin/phpunit.bat
	modified:   vendor/composer/ClassLoader.php
	modified:   vendor/composer/autoload_files.php
	modified:   vendor/composer/autoload_real.php
	modified:   vendor/composer/installed.json
	modified:   vendor/guzzle/guzzle/tests/Guzzle/Tests/Http/RedirectPluginTest.php
	modified:   vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php
	modified:   vendor/omnipay/common/src/Omnipay/Common/Message/AbstractResponse.php
	deleted:    vendor/phpunit/php-timer/Tests/TimerTest.php
	modified:   vendor/phpunit/phpunit/build/assertions.php
	modified:   vendor/phpunit/phpunit/composer/bin/phpunit
	modified:   vendor/phpunit/phpunit/phpunit.php
	modified:   vendor/squizlabs/php_codesniffer/scripts/phpcs
	modified:   vendor/squizlabs/php_codesniffer/scripts/phpcs-svn-pre-commit
	modified:   vendor/squizlabs/php_codesniffer/scripts/phpcs.bat
	deleted:    vendor/symfony/http-foundation/Tests/ClockMock.php


The file modifications all look fine, but I'm not sure about the deleted files.

**Comment by ginkgomzd** [comment]
in danger of being annoying...

Since a lot of the dependencies are tracking development branches, wouldn't it be best for folks to have the latest? 

Shouldn't master expect the audience to be developers? The tags or release branches could contain the vendor folder and just not commit it to development branches...

Cheers!

**Comment by eileenmcnaughton** [comment]
An audience! wow - I'm moving up.

I think you're probably right - but I haven't really gotten there in terms of a release cycle. Usually the release cycle is pretty chaotic / erratic & very task driven. I'm currently trying to get confirmation that NAB is all working & then I would add a release - but the customer is hitting something I didn't in my testing as yet.

**Comment by ginkgomzd** [comment]
What do you think about those files that were not restored by composer install?

**Comment by eileenmcnaughton** [comment]
I think they are hurting my brain but if I put my fingers in my ears & go la-la-la-la it will all go away...

It's also possible I did a composer update & committed the results of git add . rather than git add . -A last time...

**Comment by ginkgomzd** [comment]
I sympathize. ;-)

I think that as long as these are legitimate composer packages, or don't have manual patches or modifications...it won't be hard to get them cleaned up.

Cheers

**Comment by eileenmcnaughton** [comment]
I'm not guilty of manual edits (phew) although I have a PR just come in that I think might be doing that so I'll need to check it.

NB - I tend to run update & check that in before each deliberate change -i.e new package

**Comment by eileenmcnaughton** [comment]
I just did a composer update & got a different set again - I did a delete & then ran composer install & got a few further small changes - odd!

https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/commit/e057434b5f6b12034acc7efc730f780423812675

**Comment by ginkgomzd** [comment]
I noticed that composer install will confirm that a package is present but not update it. Composer update will check the rules in the install.json and fetch latest versions that satisfy the requirements.

It is odd that an install after an update would find changes...looked at the commit... tldr;

**Comment by xurizaemon** [comment]
I ran into this one tonight when I wanted to get started on #34.

AFAICT from the above comments, `vendor/` is committed because the release cycle is download zip from Github? Is the next step for this issue that we get a script/process to build releases, so reduces what needs to be committed in this ext?

**Comment by eileenmcnaughton** [comment]
As far as I know there is not a process yet for installing extensions & running composer in the process - so to make them downloadable they need the vendor dir installed. Having said that, Mosaico could have plumbed new ground in this area.

I have tried to upstream all the changes I've made - although the Authorize.net ones, in particular, are difficult to upstream

**Comment by xurizaemon** [comment]
I agree with what you say above. I'm not suggesting we distribute the package without `vendor/*`, only supporting my read of this issue: that those files be removed from this repo in favour of using composer.json.

I think the ideal outcome is:

- this git repo should contain composer.json, optionally composer.lock, but no vendor dir.
- the distributed zipfiles would contain the vendor dir, possibly with some cleaning (remove eg tests/, .git from child directories if so desired).

To me that:

- Reduces "noise" of many hundred file commits (since that's really just a bunch of references to things like `alfaproject/omnipay-skrill@41a7a03c`), making the actual code in this extension more readable.
- Helps support our changes getting upstreamed. So an authnet change like ba9d3fda will be one of three things: accepted upstream in omnipay/authorize-net, PRd upstream but not accepted yet, or part of our fork of omnipay/authorize-net (presumably rejected or not acceptable, maybe because we need to make a case with CiviCRM or Omnipay to align interfaces). Updating packages becomes easier with this on the surface.
- Potentially reduces the amount of code that gets shipped with the extension, which has advantages (filesize, or situations like in the past where CiviCRM had packages shipping with random & unsafe PHP example code).

If you don't object to that end goal, we can work towards it. I see this issue hasn't had attention for a couple of years. I ran straight into it as a new Omnipay developer, and figured it might be an opportunity to improve DX for all those working on it.

**Comment by eileenmcnaughton** [comment]
So CiviCRM picks up the extension directly from github. I just tag a release when updates have happened & people can automatically install that through the interface.

I think it would be great if the CiviCRM extensions deployment process could generate the download from the composer files without vendor directory committed.

OTOH I'm nervous about a process that would require me to do some mucking around with the github zip file & try to get Civi to pick that up, mostly because, simple as the process currently is, I make mistakes tagging a new release about 80% of the time (mostly not incrementing the .info file version ). I'm not sure if that is what you are suggesting?

As I mentioned previously, @totten has done more advanced packaging stuff on Mosaico that was previously done & there might be some better options now.

**Comment by eileenmcnaughton** [comment]
Closing this as I think one day a core fix will make this more do-able - but it's really a core change needed before any changes here
